/*
 * Project: Pizza Road
 * File: DashboardCustomers
 *
 * Created by fattazzo
 * Copyright © 2020 Gianluca Fattarsi. All rights reserved.
 *
 * MIT License
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/*
 * PizzaShop
 * <h1>REST API for managing a pizzeria.</h1> <br>  The application includes the management of:  <ul>     <li>users (workers and customers)</li>     <li>company branches</li>     <li>products (variations like doughs, dimensions and toppings, categories)</li>     <li>orders (creation, management)</li> <ul>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: gianluca.fattarsi@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.pizzaroad.openapi.models;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * DashboardCustomers
 */


public class DashboardCustomers {
  @SerializedName("total")
  private Integer total = null;

  @SerializedName("toConfirm")
  private Integer toConfirm = null;

  public DashboardCustomers total(Integer total) {
    this.total = total;
    return this;
  }

   /**
   * Total user of type &#x27;Customer&#x27;
   * @return total
  **/
  @Schema(required = true, description = "Total user of type 'Customer'")
  public Integer getTotal() {
    return total;
  }

  public void setTotal(Integer total) {
    this.total = total;
  }

  public DashboardCustomers toConfirm(Integer toConfirm) {
    this.toConfirm = toConfirm;
    return this;
  }

   /**
   * Number of &#x27;Customer&#x27; users who need to confirm registration
   * @return toConfirm
  **/
  @Schema(required = true, description = "Number of 'Customer' users who need to confirm registration")
  public Integer getToConfirm() {
    return toConfirm;
  }

  public void setToConfirm(Integer toConfirm) {
    this.toConfirm = toConfirm;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DashboardCustomers dashboardCustomers = (DashboardCustomers) o;
    return Objects.equals(this.total, dashboardCustomers.total) &&
        Objects.equals(this.toConfirm, dashboardCustomers.toConfirm);
  }

  @Override
  public int hashCode() {
    return Objects.hash(total, toConfirm);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DashboardCustomers {\n");
    
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    toConfirm: ").append(toIndentedString(toConfirm)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
