/*
 * Project: Pizza Road
 * File: OrderRequest
 *
 * Created by fattazzo
 * Copyright © 2020 Gianluca Fattarsi. All rights reserved.
 *
 * MIT License
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/*
 * PizzaShop
 * <h1>REST API for managing a pizzeria.</h1> <br>  The application includes the management of:  <ul>     <li>users (workers and customers)</li>     <li>company branches</li>     <li>products (variations like doughs, dimensions and toppings, categories)</li>     <li>orders (creation, management)</li> <ul>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: gianluca.fattarsi@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.pizzaroad.openapi.models;

import com.google.gson.annotations.SerializedName;

import org.threeten.bp.OffsetDateTime;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * OrderRequest
 */


public class OrderRequest {
  @SerializedName("transactionId")
  private String transactionId = null;

  @SerializedName("customerNote")
  private String customerNote = null;

  @SerializedName("backofficeNote")
  private String backofficeNote = null;

  @SerializedName("dateRequest")
  private OffsetDateTime dateRequest = null;

  @SerializedName("dateCreation")
  private OffsetDateTime dateCreation = null;

  @SerializedName("dateRequestConfirmed")
  private OffsetDateTime dateRequestConfirmed = null;

  @SerializedName("total")
  private BigDecimal total = null;

  @SerializedName("deliveryAddress")
  private Address deliveryAddress = null;

  @SerializedName("shippingMethodId")
  private Integer shippingMethodId = null;

  @SerializedName("lines")
  private List<OrderLineRequest> lines = new ArrayList<OrderLineRequest>();

  @SerializedName("shippingType")
  private ShippingType shippingType = null;

  public OrderRequest transactionId(String transactionId) {
    this.transactionId = transactionId;
    return this;
  }

   /**
   * Get transactionId
   * @return transactionId
  **/
  @Schema(description = "")
  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }

  public OrderRequest customerNote(String customerNote) {
    this.customerNote = customerNote;
    return this;
  }

   /**
   * Get customerNote
   * @return customerNote
  **/
  @Schema(description = "")
  public String getCustomerNote() {
    return customerNote;
  }

  public void setCustomerNote(String customerNote) {
    this.customerNote = customerNote;
  }

  public OrderRequest backofficeNote(String backofficeNote) {
    this.backofficeNote = backofficeNote;
    return this;
  }

   /**
   * Get backofficeNote
   * @return backofficeNote
  **/
  @Schema(description = "")
  public String getBackofficeNote() {
    return backofficeNote;
  }

  public void setBackofficeNote(String backofficeNote) {
    this.backofficeNote = backofficeNote;
  }

  public OrderRequest dateRequest(OffsetDateTime dateRequest) {
    this.dateRequest = dateRequest;
    return this;
  }

   /**
   * Get dateRequest
   * @return dateRequest
  **/
  @Schema(required = true, description = "")
  public OffsetDateTime getDateRequest() {
    return dateRequest;
  }

  public void setDateRequest(OffsetDateTime dateRequest) {
    this.dateRequest = dateRequest;
  }

  public OrderRequest dateCreation(OffsetDateTime dateCreation) {
    this.dateCreation = dateCreation;
    return this;
  }

   /**
   * Get dateCreation
   * @return dateCreation
  **/
  @Schema(required = true, description = "")
  public OffsetDateTime getDateCreation() {
    return dateCreation;
  }

  public void setDateCreation(OffsetDateTime dateCreation) {
    this.dateCreation = dateCreation;
  }

  public OrderRequest dateRequestConfirmed(OffsetDateTime dateRequestConfirmed) {
    this.dateRequestConfirmed = dateRequestConfirmed;
    return this;
  }

   /**
   * Get dateRequestConfirmed
   * @return dateRequestConfirmed
  **/
  @Schema(description = "")
  public OffsetDateTime getDateRequestConfirmed() {
    return dateRequestConfirmed;
  }

  public void setDateRequestConfirmed(OffsetDateTime dateRequestConfirmed) {
    this.dateRequestConfirmed = dateRequestConfirmed;
  }

  public OrderRequest total(BigDecimal total) {
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @Schema(description = "")
  public BigDecimal getTotal() {
    return total;
  }

  public void setTotal(BigDecimal total) {
    this.total = total;
  }

  public OrderRequest deliveryAddress(Address deliveryAddress) {
    this.deliveryAddress = deliveryAddress;
    return this;
  }

   /**
   * Get deliveryAddress
   * @return deliveryAddress
  **/
  @Schema(description = "")
  public Address getDeliveryAddress() {
    return deliveryAddress;
  }

  public void setDeliveryAddress(Address deliveryAddress) {
    this.deliveryAddress = deliveryAddress;
  }

  public OrderRequest shippingMethodId(Integer shippingMethodId) {
    this.shippingMethodId = shippingMethodId;
    return this;
  }

   /**
   * Get shippingMethodId
   * @return shippingMethodId
  **/
  @Schema(required = true, description = "")
  public Integer getShippingMethodId() {
    return shippingMethodId;
  }

  public void setShippingMethodId(Integer shippingMethodId) {
    this.shippingMethodId = shippingMethodId;
  }

  public OrderRequest lines(List<OrderLineRequest> lines) {
    this.lines = lines;
    return this;
  }

  public OrderRequest addLinesItem(OrderLineRequest linesItem) {
    this.lines.add(linesItem);
    return this;
  }

   /**
   * Get lines
   * @return lines
  **/
  @Schema(required = true, description = "")
  public List<OrderLineRequest> getLines() {
    return lines;
  }

  public void setLines(List<OrderLineRequest> lines) {
    this.lines = lines;
  }

  public OrderRequest shippingType(ShippingType shippingType) {
    this.shippingType = shippingType;
    return this;
  }

   /**
   * Get shippingType
   * @return shippingType
  **/
  @Schema(required = true, description = "")
  public ShippingType getShippingType() {
    return shippingType;
  }

  public void setShippingType(ShippingType shippingType) {
    this.shippingType = shippingType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderRequest orderRequest = (OrderRequest) o;
    return Objects.equals(this.transactionId, orderRequest.transactionId) &&
        Objects.equals(this.customerNote, orderRequest.customerNote) &&
        Objects.equals(this.backofficeNote, orderRequest.backofficeNote) &&
        Objects.equals(this.dateRequest, orderRequest.dateRequest) &&
        Objects.equals(this.dateCreation, orderRequest.dateCreation) &&
        Objects.equals(this.dateRequestConfirmed, orderRequest.dateRequestConfirmed) &&
        Objects.equals(this.total, orderRequest.total) &&
        Objects.equals(this.deliveryAddress, orderRequest.deliveryAddress) &&
        Objects.equals(this.shippingMethodId, orderRequest.shippingMethodId) &&
        Objects.equals(this.lines, orderRequest.lines) &&
        Objects.equals(this.shippingType, orderRequest.shippingType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionId, customerNote, backofficeNote, dateRequest, dateCreation, dateRequestConfirmed, total, deliveryAddress, shippingMethodId, lines, shippingType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderRequest {\n");
    
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    customerNote: ").append(toIndentedString(customerNote)).append("\n");
    sb.append("    backofficeNote: ").append(toIndentedString(backofficeNote)).append("\n");
    sb.append("    dateRequest: ").append(toIndentedString(dateRequest)).append("\n");
    sb.append("    dateCreation: ").append(toIndentedString(dateCreation)).append("\n");
    sb.append("    dateRequestConfirmed: ").append(toIndentedString(dateRequestConfirmed)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    deliveryAddress: ").append(toIndentedString(deliveryAddress)).append("\n");
    sb.append("    shippingMethodId: ").append(toIndentedString(shippingMethodId)).append("\n");
    sb.append("    lines: ").append(toIndentedString(lines)).append("\n");
    sb.append("    shippingType: ").append(toIndentedString(shippingType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
