/*
 * Project: Pizza Road
 * File: OrderLineRequest
 *
 * Created by fattazzo
 * Copyright © 2020 Gianluca Fattarsi. All rights reserved.
 *
 * MIT License
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/*
 * PizzaShop
 * <h1>REST API for managing a pizzeria.</h1> <br>  The application includes the management of:  <ul>     <li>users (workers and customers)</li>     <li>company branches</li>     <li>products (variations like doughs, dimensions and toppings, categories)</li>     <li>orders (creation, management)</li> <ul>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: gianluca.fattarsi@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.pizzaroad.openapi.models;

import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * OrderLineRequest
 */


public class OrderLineRequest {
  @SerializedName("quantity")
  private Integer quantity = null;

  @SerializedName("customerNote")
  private String customerNote = null;

  @SerializedName("total")
  private BigDecimal total = null;

  @SerializedName("itemId")
  private Integer itemId = null;

  @SerializedName("pizzaDoughId")
  private Integer pizzaDoughId = null;

  @SerializedName("pizzaPriceId")
  private Integer pizzaPriceId = null;

  @SerializedName("pizzaToppingExtrasId")
  private List<Integer> pizzaToppingExtrasId = null;

  @SerializedName("productPriceId")
  private Integer productPriceId = null;

  public OrderLineRequest quantity(Integer quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @Schema(required = true, description = "")
  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }

  public OrderLineRequest customerNote(String customerNote) {
    this.customerNote = customerNote;
    return this;
  }

   /**
   * Get customerNote
   * @return customerNote
  **/
  @Schema(description = "")
  public String getCustomerNote() {
    return customerNote;
  }

  public void setCustomerNote(String customerNote) {
    this.customerNote = customerNote;
  }

  public OrderLineRequest total(BigDecimal total) {
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @Schema(required = true, description = "")
  public BigDecimal getTotal() {
    return total;
  }

  public void setTotal(BigDecimal total) {
    this.total = total;
  }

  public OrderLineRequest itemId(Integer itemId) {
    this.itemId = itemId;
    return this;
  }

   /**
   * Get itemId
   * @return itemId
  **/
  @Schema(required = true, description = "")
  public Integer getItemId() {
    return itemId;
  }

  public void setItemId(Integer itemId) {
    this.itemId = itemId;
  }

  public OrderLineRequest pizzaDoughId(Integer pizzaDoughId) {
    this.pizzaDoughId = pizzaDoughId;
    return this;
  }

   /**
   * Get pizzaDoughId
   * @return pizzaDoughId
  **/
  @Schema(description = "")
  public Integer getPizzaDoughId() {
    return pizzaDoughId;
  }

  public void setPizzaDoughId(Integer pizzaDoughId) {
    this.pizzaDoughId = pizzaDoughId;
  }

  public OrderLineRequest pizzaPriceId(Integer pizzaPriceId) {
    this.pizzaPriceId = pizzaPriceId;
    return this;
  }

   /**
   * Get pizzaPriceId
   * @return pizzaPriceId
  **/
  @Schema(description = "")
  public Integer getPizzaPriceId() {
    return pizzaPriceId;
  }

  public void setPizzaPriceId(Integer pizzaPriceId) {
    this.pizzaPriceId = pizzaPriceId;
  }

  public OrderLineRequest pizzaToppingExtrasId(List<Integer> pizzaToppingExtrasId) {
    this.pizzaToppingExtrasId = pizzaToppingExtrasId;
    return this;
  }

  public OrderLineRequest addPizzaToppingExtrasIdItem(Integer pizzaToppingExtrasIdItem) {
    if (this.pizzaToppingExtrasId == null) {
      this.pizzaToppingExtrasId = new ArrayList<Integer>();
    }
    this.pizzaToppingExtrasId.add(pizzaToppingExtrasIdItem);
    return this;
  }

   /**
   * Get pizzaToppingExtrasId
   * @return pizzaToppingExtrasId
  **/
  @Schema(description = "")
  public List<Integer> getPizzaToppingExtrasId() {
    return pizzaToppingExtrasId;
  }

  public void setPizzaToppingExtrasId(List<Integer> pizzaToppingExtrasId) {
    this.pizzaToppingExtrasId = pizzaToppingExtrasId;
  }

  public OrderLineRequest productPriceId(Integer productPriceId) {
    this.productPriceId = productPriceId;
    return this;
  }

   /**
   * Get productPriceId
   * @return productPriceId
  **/
  @Schema(description = "")
  public Integer getProductPriceId() {
    return productPriceId;
  }

  public void setProductPriceId(Integer productPriceId) {
    this.productPriceId = productPriceId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderLineRequest orderLineRequest = (OrderLineRequest) o;
    return Objects.equals(this.quantity, orderLineRequest.quantity) &&
        Objects.equals(this.customerNote, orderLineRequest.customerNote) &&
        Objects.equals(this.total, orderLineRequest.total) &&
        Objects.equals(this.itemId, orderLineRequest.itemId) &&
        Objects.equals(this.pizzaDoughId, orderLineRequest.pizzaDoughId) &&
        Objects.equals(this.pizzaPriceId, orderLineRequest.pizzaPriceId) &&
        Objects.equals(this.pizzaToppingExtrasId, orderLineRequest.pizzaToppingExtrasId) &&
        Objects.equals(this.productPriceId, orderLineRequest.productPriceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(quantity, customerNote, total, itemId, pizzaDoughId, pizzaPriceId, pizzaToppingExtrasId, productPriceId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderLineRequest {\n");
    
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    customerNote: ").append(toIndentedString(customerNote)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    itemId: ").append(toIndentedString(itemId)).append("\n");
    sb.append("    pizzaDoughId: ").append(toIndentedString(pizzaDoughId)).append("\n");
    sb.append("    pizzaPriceId: ").append(toIndentedString(pizzaPriceId)).append("\n");
    sb.append("    pizzaToppingExtrasId: ").append(toIndentedString(pizzaToppingExtrasId)).append("\n");
    sb.append("    productPriceId: ").append(toIndentedString(productPriceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
