/*
 * Project: Pizza Road
 * File: Settings
 *
 * Created by fattazzo
 * Copyright © 2020 Gianluca Fattarsi. All rights reserved.
 *
 * MIT License
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/*
 * PizzaShop
 * <h1>REST API for managing a pizzeria.</h1> <br>  The application includes the management of:  <ul>     <li>users (workers and customers)</li>     <li>company branches</li>     <li>products (variations like doughs, dimensions and toppings, categories)</li>     <li>orders (creation, management)</li> <ul>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: gianluca.fattarsi@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.pizzaroad.openapi.models;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Settings
 */


public class Settings {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("currencySymbol")
  private String currencySymbol = null;

  @SerializedName("currencyDecimals")
  private Integer currencyDecimals = null;

  @SerializedName("minOrderRequestMinutes")
  private Integer minOrderRequestMinutes = null;

  @SerializedName("processingOrdersMinutesPartition")
  private Integer processingOrdersMinutesPartition = null;

  public Settings id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier
   * @return id
  **/
  @Schema(description = "Unique identifier")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Settings currencySymbol(String currencySymbol) {
    this.currencySymbol = currencySymbol;
    return this;
  }

   /**
   * Currency symbol
   * @return currencySymbol
  **/
  @Schema(required = true, description = "Currency symbol")
  public String getCurrencySymbol() {
    return currencySymbol;
  }

  public void setCurrencySymbol(String currencySymbol) {
    this.currencySymbol = currencySymbol;
  }

  public Settings currencyDecimals(Integer currencyDecimals) {
    this.currencyDecimals = currencyDecimals;
    return this;
  }

   /**
   * Number of decimals used for currency
   * minimum: 0
   * maximum: 5
   * @return currencyDecimals
  **/
  @Schema(required = true, description = "Number of decimals used for currency")
  public Integer getCurrencyDecimals() {
    return currencyDecimals;
  }

  public void setCurrencyDecimals(Integer currencyDecimals) {
    this.currencyDecimals = currencyDecimals;
  }

  public Settings minOrderRequestMinutes(Integer minOrderRequestMinutes) {
    this.minOrderRequestMinutes = minOrderRequestMinutes;
    return this;
  }

   /**
   * Minimum time in minutes to request the order
   * minimum: 0
   * @return minOrderRequestMinutes
  **/
  @Schema(required = true, description = "Minimum time in minutes to request the order")
  public Integer getMinOrderRequestMinutes() {
    return minOrderRequestMinutes;
  }

  public void setMinOrderRequestMinutes(Integer minOrderRequestMinutes) {
    this.minOrderRequestMinutes = minOrderRequestMinutes;
  }

  public Settings processingOrdersMinutesPartition(Integer processingOrdersMinutesPartition) {
    this.processingOrdersMinutesPartition = processingOrdersMinutesPartition;
    return this;
  }

   /**
   * Get processingOrdersMinutesPartition
   * @return processingOrdersMinutesPartition
  **/
  @Schema(required = true, description = "")
  public Integer getProcessingOrdersMinutesPartition() {
    return processingOrdersMinutesPartition;
  }

  public void setProcessingOrdersMinutesPartition(Integer processingOrdersMinutesPartition) {
    this.processingOrdersMinutesPartition = processingOrdersMinutesPartition;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Settings settings = (Settings) o;
    return Objects.equals(this.id, settings.id) &&
        Objects.equals(this.currencySymbol, settings.currencySymbol) &&
        Objects.equals(this.currencyDecimals, settings.currencyDecimals) &&
        Objects.equals(this.minOrderRequestMinutes, settings.minOrderRequestMinutes) &&
        Objects.equals(this.processingOrdersMinutesPartition, settings.processingOrdersMinutesPartition);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, currencySymbol, currencyDecimals, minOrderRequestMinutes, processingOrdersMinutesPartition);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Settings {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    currencySymbol: ").append(toIndentedString(currencySymbol)).append("\n");
    sb.append("    currencyDecimals: ").append(toIndentedString(currencyDecimals)).append("\n");
    sb.append("    minOrderRequestMinutes: ").append(toIndentedString(minOrderRequestMinutes)).append("\n");
    sb.append("    processingOrdersMinutesPartition: ").append(toIndentedString(processingOrdersMinutesPartition)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
