/*
 * Project: Pizza Road
 * File: ShippingMethod
 *
 * Created by fattazzo
 * Copyright © 2020 Gianluca Fattarsi. All rights reserved.
 *
 * MIT License
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/*
 * PizzaShop
 * <h1>REST API for managing a pizzeria.</h1> <br>  The application includes the management of:  <ul>     <li>users (workers and customers)</li>     <li>company branches</li>     <li>products (variations like doughs, dimensions and toppings, categories)</li>     <li>orders (creation, management)</li> <ul>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: gianluca.fattarsi@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.pizzaroad.openapi.models;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * ShippingMethod
 */


public class ShippingMethod {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("type")
  private ShippingMethodType type = null;

  @SerializedName("enabled")
  private Boolean enabled = null;

  @SerializedName("shippingTypes")
  private List<ShippingType> shippingTypes = new ArrayList<ShippingType>();

  public ShippingMethod id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Method ID
   * @return id
  **/
  @Schema(description = "Method ID")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public ShippingMethod title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Shipping method title
   * @return title
  **/
  @Schema(required = true, description = "Shipping method title")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public ShippingMethod description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Shipping method description
   * @return description
  **/
  @Schema(description = "Shipping method description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ShippingMethod type(ShippingMethodType type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(required = true, description = "")
  public ShippingMethodType getType() {
    return type;
  }

  public void setType(ShippingMethodType type) {
    this.type = type;
  }

  public ShippingMethod enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Get enabled
   * @return enabled
  **/
  @Schema(required = true, description = "")
  public Boolean isEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  public ShippingMethod shippingTypes(List<ShippingType> shippingTypes) {
    this.shippingTypes = shippingTypes;
    return this;
  }

  public ShippingMethod addShippingTypesItem(ShippingType shippingTypesItem) {
    this.shippingTypes.add(shippingTypesItem);
    return this;
  }

   /**
   * Get shippingTypes
   * @return shippingTypes
  **/
  @Schema(required = true, description = "")
  public List<ShippingType> getShippingTypes() {
    return shippingTypes;
  }

  public void setShippingTypes(List<ShippingType> shippingTypes) {
    this.shippingTypes = shippingTypes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShippingMethod shippingMethod = (ShippingMethod) o;
    return Objects.equals(this.id, shippingMethod.id) &&
        Objects.equals(this.title, shippingMethod.title) &&
        Objects.equals(this.description, shippingMethod.description) &&
        Objects.equals(this.type, shippingMethod.type) &&
        Objects.equals(this.enabled, shippingMethod.enabled) &&
        Objects.equals(this.shippingTypes, shippingMethod.shippingTypes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, title, description, type, enabled, shippingTypes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShippingMethod {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    shippingTypes: ").append(toIndentedString(shippingTypes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
